// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    this.initConfig({
      CSS_DIR: 'lib/template/src/css/',
      CSS_DEBUG_FILE: '<%= CSS_DIR %>docs.css',
      CSS_MIN_FILE: 'lib/template/css/docs.min.css',
      JS_DIR: 'lib/template/src/js/',
      JS_FILE: 'lib/template/js/docs.min.js',
      jshint: {
        options: {
          jshintrc: '.jshintrc'
        },
        lib: {
          src: ['lib/comment.js', 'lib/doc.js', '<%= JS_DIR %>tocfilter.js']
        }
      },
      stylus: {
        compile: {
          files: {
            '<%= CSS_DEBUG_FILE %>': ['<%= CSS_DIR %>styl/docs.styl']
          }
        }
      },
      uglify: {
        target: {
          files: {
            '<%= JS_FILE %>': ['<%= JS_DIR %>prettify.js', '<%= JS_DIR %>tocfilter.js']
          }
        }
      },
      cssmin: {
        compress: {
          files: {
            '<%= CSS_MIN_FILE %>': ['<%= CSS_DEBUG_FILE %>']
          }
        }
      },
      watch: {
        test: {
          files: ['lib/**/*.js'],
          tasks: ['link']
        },
        jshint: {
          files: ['<%= jshint.lib.src %>'],
          tasks: ['jshint', 'uglify']
        },
        stylus: {
          files: ['<%= CSS_DIR %>styl/comment.styl', '<%= CSS_DIR %>styl/src.styl'],
          tasks: ['stylus', 'cssmin']
        }
      }
    });
    this.task.registerTask('link', 'Update module', function() {
      grunt.util.spawn({
        cmd: 'npm',
        args: ['link']
      });
      return grunt.log.write('Linked!').ok();
    });
    this.loadNpmTasks('grunt-contrib-jshint');
    this.loadNpmTasks('grunt-contrib-stylus');
    this.loadNpmTasks('grunt-contrib-cssmin');
    this.loadNpmTasks('grunt-contrib-uglify');
    this.loadNpmTasks('grunt-contrib-watch');
    return this.registerTask('default', ['jshint', 'stylus', 'uglify', 'cssmin']);
  };

}).call(this);
